# Generated by Django 3.2.6 on 2022-03-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eweather_api_controller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mac', models.CharField(max_length=17)),
            ],
        ),
    ]
