# Generated by Django 4.0.1 on 2022-01-24 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eweather_api_controller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='user',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_request',
        ),
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.CharField(default='Unknown address', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='place',
            name='lon',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('lat', 'lon', 'owner')},
        ),
        migrations.CreateModel(
            name='PlaceWeatherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('lon', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('pressure', models.IntegerField()),
                ('humidity', models.IntegerField()),
            ],
            options={
                'unique_together': {('lat', 'lon', 'timestamp')},
            },
        ),
        migrations.RemoveField(
            model_name='place',
            name='name',
        ),
    ]
